version: 0.1
loglevel: debug
storage:
  s3:
    region: us-west-1
    bucket: bucketname
    encrypt: true
    secure: true
    v4auth: true
    chunksize: 5242880
    rootdirectory: /registry_data
  delete:
    enabled: true
  cache:
    blobdescriptor: redis
http:
  addr: 0.0.0.0:5000
  debug:
    addr: 0.0.0.0:5001
  headers:
    X-Content-Type-Options: [nosniff]
redis:
  addr: 172.17.42.1:6379
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
auth:
  token:
    realm: http://172.17.42.1:3000/v2/token
    service: 172.17.42.1:5000
    issuer: portus.test.lan
    rootcertbundle: /etc/docker/registry/portus.crt
notifications:
  endpoints:
    - name: portus
      url: http://172.17.42.1:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3